language: python
python:
  - "2.7"
install:
  - sudo apt-get install libffi-dev libssl-dev
  - python setup.py develop
services:
  - mongodb
before_script:
  - cp tests.cfg.default tests.cfg
script: ./run_tests
