language: python
python:
  - "2.7"
install:
  - sudo apt-get install libffi-dev libssl-dev
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.0.2 mongodb-org-server=3.0.2 mongodb-org-shell=3.0.2 mongodb-org-mongos=3.0.2 mongodb-org-tools=3.0.2
  - python setup.py develop
before_script:
  - cp tests.cfg.default tests.cfg
  - sudo service mongod restart
  - mongo --eval "db.version()"
script: ./run_tests
